# Generated by Django 3.1.2 on 2020-10-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(blank=True, max_length=30, null=True)),
                ('st_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('stu_type', models.CharField(blank=True, choices=[('REGULAR', 'REGULAR'), ('RETAKE', 'RETAKE')], default=('REGULAR', 'REGULAR'), max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('semester_name', models.CharField(blank=True, max_length=20, null=True)),
                ('credit', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('credit_hour', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('REGULAR', 'REGULAR'), ('RETAKE', 'RETAKE')], default=('REGULAR', 'REGULAR'), max_length=30)),
                ('remarks', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_app.studentregistration')),
            ],
        ),
    ]
