# Generated by Django 3.1.2 on 2020-10-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenroll',
            name='course_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='st_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
