# Generated by Django 3.1.2 on 2020-10-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=30)),
                ('st_id', models.CharField(max_length=20)),
                ('stu_type', models.CharField(choices=[('REGULAR', 'REGULAR'), ('RETAKE', 'RETAKE')], default=('REGULAR', 'REGULAR'), max_length=30)),
                ('department', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('semester_name', models.CharField(max_length=20)),
                ('credit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('credit_hour', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('REGULAR', 'REGULAR'), ('RETAKE', 'RETAKE')], default=('REGULAR', 'REGULAR'), max_length=30)),
                ('remarks', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_app.courseregistration')),
            ],
        ),
    ]
