# Generated by Django 3.1.2 on 2020-10-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0002_courseenroll_courseregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='st_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
