# Generated by Django 3.1.2 on 2020-10-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0003_auto_20201022_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='stu_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
